
#1.
# - name: Variables in ply level
#   hosts: local
#   connection: local
#   vars:
#     NAME: "Nagendra"
#     AGE: 25

#   tasks:
#   - name: Variables form play level
#     ansible.builtin.debug:
#      msg: "My name is {{ NAME }}, age {{ AGE }} - play level"    

#2.
# - name: Variables in task level 
#   hosts: local
#   connection: local
#   tasks:
#   - name: variables at task level
#     vars:
#      NAME: "Nagendra"
#      AGE: 25
#     ansible.builtin.debug:
#      msg: "My name is {{ NAME }}, age {{ AGE }} - task level"

#3.

# - name: varaibles from var_files
#   hosts: local
#   connection: local
#   vars_files:
#   - details.yaml
#   tasks:
#   - name: variables From separate files
#     vars:
#      NAME: "Nagendra"
#      AGE: 25
#     ansible.builtin.debug:
#      msg: "My name is {{ NAME }}, age {{ AGE }} - file level"


#4. pass variables as prompt 

# - name: variables from prompts
#   hosts: local
#   connection: local
#   vars_prompt:
#   - name: NAME
#     prompt: enter name
#     private: false

#   - name: AGE
#     prompt: enter age
#     private: true

#   tasks:
#   - name: varaibles from args
#     ansible.builtin.debug:
#      msg: "My name is {{ NAME }}, age {{ AGE }} - prompt level"


#5. pass variables from inventory file in inventory.ini in this file provided the variables.

# - name: Variables from inventory file
#   hosts: local
#   connection: local
#   tasks:
#   - name: varaibles from inventory file
#     ansible.builtin.debug:
#      msg: "My name is {{ NAME }}, age {{ AGE }} - inventory file level"


#6. varables from args directly 

- name: Variables from args 
  hosts: local
  connection: local
  tasks:
  - name: varaibles from arguments
    ansible.builtin.debug:
     msg: "My name is {{ NAME }}, age {{ AGE }} - variable arguments"

     # ansible-playbook -i inventory.ini -e NAME=nagendra -e AGE=25 02-variables.yaml
