- name: gathering facts
  hosts: local
  connection: local
  tasks:
  - name: print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: Check os family
    ansible.builtin.debug:
      msg: "Package manager is redhat"
    when: ansible_facts.os_family == "RedHat"      