- name:
  hosts: local
  connection: local
  become: yes   # providing root access
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "mysql", state: "absent"}
    - { name: "nginx", state: "present"}