- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item}}"       # item need to give for loops.
      state: installed

    # list of string 
    loop:
    - nginx
    - mysql