- name: Create user if not exists from dynamic input
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: "Please enter username"
      private: false
    
    - name: DIR_NAME
      prompt: "Please enter Directory name"
      private: false  

  vars:
    PATH: "/temp"    

  tasks:
  - name: check the user exist or not
    ansible.builtin.command: id.{{USERNAME}}
    register: out
    ignore_errors: true

  - name:  print the command output
    ansible.builtin.debug:
      msg: 
        - "output is: {{out}}"  
        - "Exit code is: {{out.rc}}"  

  - name: create new user
    become: yes
    ansible.builtin.user:
      name: "{{USERNAME}}"

    when: out.rc !=0  

############################################

  - name: check the directory exist or not
    ansible.builtin.stat: 
    path: "{{PATH}}"
    register: dir_to_check
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "The directory was: {{dir_to_check}}"  

