- name: Create user if not exists from dynamic input
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: "Please enter username"
      private: false

  tasks:
  - name: check the user exist or not
    ansible.builtin.command: id.{{USERNAME}}
    register: out
    ignore_errors: true

  - name:  print the command output
    ansible.builtin.debug:
      msg: 
        - "output is: {{out}}"  
        - "Exit code is: {{out.rc}}"  

  - name: create new user
    become: yes
    ansible.builtin.user:
      name: USERNAME

    when: out.rc !=0        